# Generated by Django 3.2.8 on 2021-10-20 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListaZglaszajacych',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_zglaszajacego', models.DecimalField(decimal_places=0, max_digits=4, unique=True)),
                ('aktywny', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RodzajUsterki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj_usterki', models.CharField(max_length=60)),
                ('aktywny', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Urzadzenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_urzadzenia', models.CharField(max_length=80)),
                ('aktywny', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZgloszenieUsterki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zgloszenia', models.DateField(verbose_name='data zgłoszenia')),
                ('czas_zgloszenia', models.TimeField(verbose_name='czas zgłoszenia')),
                ('zglaszajacy', models.DecimalField(decimal_places=0, max_digits=4, unique=True)),
                ('temat_zgloszenia', models.CharField(max_length=400)),
                ('opis_zgloszenia', models.TextField()),
                ('status', models.DecimalField(decimal_places=0, max_digits=1)),
                ('data_otwarcia', models.DateField(verbose_name='data otwarcia')),
                ('czas_otwarcia', models.TimeField(verbose_name='czas otwarcia')),
                ('opis_rozwiazania', models.TextField()),
                ('data_zamkniecia', models.DateField(verbose_name='data zamknięcia')),
                ('czas_zamkniecia', models.TimeField(verbose_name='czas zamknięcia')),
                ('rodzaj_usterki', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='serwis.rodzajusterki')),
                ('serwisant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='serwis.autor')),
                ('urzadzenie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='serwis.urzadzenie')),
            ],
        ),
    ]
