# Generated by Django 3.2.8 on 2021-10-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serwis', '0002_alter_zgloszenieusterki_zglaszajacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='serwisant',
            field=models.BooleanField(default=False),
        ),
    ]
