# Generated by Django 3.2.8 on 2021-10-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serwis', '0003_autor_serwisant'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='aktywny',
            field=models.BooleanField(default=True),
        ),
    ]
